apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: biteiq-release-5
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/agustinkiko/BiteIQ.git
  ref:
    tag: biteiq-release-5
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: biteiq-database
  namespace: flux-system
spec:
  interval: 5m
  path: ./deploy/k8s/homelab/database
  prune: false
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: biteiq-release-5
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: biteiq-migration-release-5
  namespace: flux-system
  labels:
    biteiq-release: main-589fa8718294735aedc134308206b4aad57d5fe0-4
spec:
  interval: 5m
  path: ./deploy/k8s/homelab/migration
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: biteiq-release-5
  dependsOn:
    - name: biteiq-database
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: biteiq-app
  namespace: flux-system
  labels:
    biteiq-release: main-589fa8718294735aedc134308206b4aad57d5fe0-4
spec:
  interval: 5m
  path: ./deploy/k8s/homelab/app
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: biteiq-release-5
  dependsOn:
    - name: biteiq-migration-release-5
      readyExpr: >-
        dep.metadata.labels['biteiq-release'] == self.metadata.labels['biteiq-release'] &&
        dep.status.conditions.exists(e, e.type == 'Ready' && e.status == 'True') &&
        dep.metadata.generation == dep.status.observedGeneration
