apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: biteiq
resources:
  - namespace.yaml
  - api-config.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - migration-job.yaml
  - api-service.yaml
  - api-deployment.yaml
  - api-ingress.yaml
