apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -release-4
images:
  - name: ghcr.io/example/biteiq-api
    newName: ghcr.io/agustinkiko/biteiq-api
    newTag: main-589fa8718294735aedc134308206b4aad57d5fe0-4
  - name: ghcr.io/example/biteiq-web
    newName: ghcr.io/agustinkiko/biteiq-web
    newTag: main-589fa8718294735aedc134308206b4aad57d5fe0-4
patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: biteiq
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: biteiq-api-config
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: biteiq-postgres
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: biteiq-postgres
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biteiq-api
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biteiq-web
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: biteiq-api
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: biteiq-web
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: biteiq-api
  - target:
      kind: Job
      name: biteiq-migrate
    patch: |-
      - op: remove
        path: /spec/ttlSecondsAfterFinished
      - op: replace
        path: /spec/template/spec/containers/0/command
        value: [node, dist/db/migrate.js]
