apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: biteiq-migrate
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biteiq-api
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: biteiq-web
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: biteiq-api
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: biteiq-web
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: biteiq-api
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: biteiq-api-config
      data:
        APP_URL: https://biteiq.jericoagustin.com
        CLIENT_ORIGINS: https://biteiq.jericoagustin.com
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: biteiq-postgres
      spec:
        template:
          spec:
            securityContext:
              runAsNonRoot: true
              runAsUser: 70
              runAsGroup: 70
              fsGroup: 70
