apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: biteiq
resources:
  - migration-job.yaml
images:
  - name: ghcr.io/example/biteiq-api
    newName: ghcr.io/example/biteiq-api
    newTag: latest
